# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_start_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartForm(object):
    def setupUi(self, StartForm):
        StartForm.setObjectName("StartForm")
        StartForm.resize(399, 148)
        StartForm.setMinimumSize(QtCore.QSize(399, 148))
        StartForm.setMaximumSize(QtCore.QSize(399, 148))
        self.main_text_label = QtWidgets.QLabel(StartForm)
        self.main_text_label.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_text_label.setFont(font)
        self.main_text_label.setObjectName("main_text_label")
        self.do_not_show_radio_button = QtWidgets.QRadioButton(StartForm)
        self.do_not_show_radio_button.setGeometry(QtCore.QRect(10, 90, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.do_not_show_radio_button.setFont(font)
        self.do_not_show_radio_button.setObjectName("do_not_show_radio_button")
        self.file_name_label = QtWidgets.QLabel(StartForm)
        self.file_name_label.setGeometry(QtCore.QRect(60, 50, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.file_name_label.setFont(font)
        self.file_name_label.setText("")
        self.file_name_label.setObjectName("file_name_label")
        self.ok_button = QtWidgets.QPushButton(StartForm)
        self.ok_button.setGeometry(QtCore.QRect(332, 90, 61, 31))
        self.ok_button.setObjectName("ok_button")
        self.show_error_label = QtWidgets.QLabel(StartForm)
        self.show_error_label.setGeometry(QtCore.QRect(10, 120, 381, 21))
        self.show_error_label.setMaximumSize(QtCore.QSize(381, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_error_label.setFont(font)
        self.show_error_label.setText("")
        self.show_error_label.setObjectName("show_error_label")
        self.tool_button = QtWidgets.QPushButton(StartForm)
        self.tool_button.setGeometry(QtCore.QRect(10, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tool_button.setFont(font)
        self.tool_button.setObjectName("tool_button")

        self.retranslateUi(StartForm)
        QtCore.QMetaObject.connectSlotsByName(StartForm)

    def retranslateUi(self, StartForm):
        _translate = QtCore.QCoreApplication.translate
        StartForm.setWindowTitle(_translate("StartForm", "Начало"))
        self.main_text_label.setText(_translate("StartForm", "Выберите папку для сохранения файлов:"))
        self.do_not_show_radio_button.setText(_translate("StartForm", "Не показывать в следующий раз"))
        self.ok_button.setText(_translate("StartForm", "OK"))
        self.tool_button.setText(_translate("StartForm", "..."))
